name: Workflow Two
on:
  workflow_run:
    workflows: ["Workflow One"] # Runs only after Workflow 1 completes
    types:
      - completed

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Runs only if Workflow 1 was successful
    runs-on: ubuntu-latest
    steps:
      - name: Download analysis results
        uses: actions/download-artifact@v4
        with:
          name: analysis-results
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: log whole github context
        run: |
          echo "GITHUB_CONTEXT: ${{ toJson(github) }}"
          echo "GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}"
          echo "GITHUB_WORKFLOW_CONTEXT: ${{ toJson(github.workflow) }}"

      - name: Get PR Number from GitHub API (for forks)
        id: get_pr_number
        run: |
          if [[ "${{ github.event.workflow_run.head_repository.fork }}" == "true" ]]; then
            echo "This is a forked repository."
            pr_number=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }}" \
              | jq '.[0].number')
            echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          else
            echo "pr_number=${{ github.event.workflow_run.pull_requests[0].number }}" >> $GITHUB_OUTPUT
          fi

      - run: |
          echo "This is a comment on the PR based on the analysis results:"
          cat result.txt
          echo ${{ steps.get_pr_number.outputs.pr_number }}
          echo "----------------------------------"
